### ISSUE TITLE
Why are we forking repository ?

### ISSUE THREAD

**Issue by smitroshin** [asmeurer/git-workflow#12]
For me is unclear, if we're working with original repository (ex. `sympy/sympy`) why we need to make fork ?
Or if we have fork, why we need to clone directly from original but not from our fork.

P.S. I'm new in open-source contribution, that's why I'm here :)

**Comment by asmeurer** [comment]
You need to fork because you won't actually have access to push to the original repository, like sympy/sympy. Only people who have push access to sympy/sympy can push to it, and even then, the sympy community prefers that everyone works against forks, so even people with push access will push things up to their forks, not directly to sympy/sympy. The fork puts a copy of the repo in your user so that you have access to push to it. 

You could clone from your fork, and indeed sometimes people recommend this instead. I prefer cloning from the original repo and adding the fork as a remote, because it's provides a uniform workflow. Say there was another repository that you just wanted to clone, but not contribute to. There would be no point in forking it first just to clone it. Instead, you can just clone the main repository and pull in the changes. If you later decide you do want to contribute, you can fork it and add that fork as a remote so that you can push your changes to the fork. 

With a workflow where you clone from your fork, you either have a different workflow between repositories you want to contribute to and repositories you just want to clone, or you have a situation where you have to do the extra unnecessary step of forking every time you clone a repository just so that your workflow is the same everywhere. Basically, with the workflow described here, you only need to do step one for a repo that you just want to clone without contributing anything, whereas with a "clone from fork" workflow you would need to do all steps, including "fork" and "add git remote", even if you don't want to contribute.

**Comment by smitroshin** [comment]
Thank you for explaining!

I tried to do your steps, but after trying to push my branch, git said that I don't have permissions to do that.
Probably `git remote add your-github-username fork-url` didn't worked.
But I decided to work with fork only.

I saw that I can do pull request from my fork to author repository.
